require("eexy")

vim.lsp.enable('lua-language-server')
vim.lsp.enable('typescript-language-server')
vim.lsp.enable('vue-language-server')
vim.lsp.enable('biome')
vim.lsp.enable('tailwind-language-server')
vim.lsp.enable('vscode-eslint-language-server')
vim.lsp.enable('rust-analyzer')
vim.lsp.enable('marksman')
vim.lsp.enable('pyright')
